### ISSUE TITLE
<Boşluk> İçeren Örnek Dosyası İsmi

### ISSUE THREAD

**Issue by erdavci** [HakkanR/SSD1306TUR#2]
Kütüphane ile birlikte gelen "writeTr 128x32_i2c" ve "writeTr 128x64_i2c" örnek dosyalarının adlarında "boşluk" bulunduğundan, Arduino IDE, ASCII olmayan, boşluk içeren veya sayı ile başlayan dosya/klasör isimlerinin kullanılamayacağını belirten bir hata mesajı veriyor ve kütüphane yüklenemiyor. Ilgili boşluk karakterlerini ASCII bir karakter ile değiştirdiğimde elbette sorun ortadan kalkıyor. Ayrıca "writeTr 128x32_i2c" örneğinin klasör ismi ile dosya ismi uyuşmuyor. Sorunu çözmek zor değil ama kütüphanenin varsayılan olarak sorunsuz gelmesi önemli bir konu. 

![ssdtr_01](https://github.com/HakkanR/SSD1306TUR/assets/84367232/6abe4b75-e4a5-4621-841c-94b081e22c2a)

Sorun ile karşılaşılan sistemin özellikleri:
Arduino IDE : 1.8.15
Windows 10 Pro 22H2

**Comment by HakkanR** [comment]
Alakanız için çok teşekkür ederim.
v1.0.2 release içinde düzelttim :)
